version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_bdUTN
    environment:
      MYSQL_ROOT_PASSWORD: utn0101
      MYSQL_DATABASE: bdUTN
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bd_network

volumes:
  db_data:

networks:
  bd_network:
    driver: bridge

